In [1]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
URL = "https://en.wikipedia.org/wiki/National_responses_to_the_2019%E2%80%9320_coronavirus_pandemic"
page = requests.get(URL)
soup = BeautifulSoup(page.text)
tables = soup.findAll("table", {"class": "wikitable"})

In [3]:
data = []

def get_text(col):
    return re.sub(r"\[[^]]+\]", "", col.text.strip())

for row in tables[2].findAll("tr"):
    columns = row.findAll("td")
    if len(columns) < 4:
        continue

    if len(columns) == 5:
        country = get_text(columns[0])
        place = get_text(columns[1])
        columns = columns[2:]
    elif "colspan" in columns[0].attrs:
        country = get_text(columns[0])
        place = ""
        columns = columns[1:]
    else:
        place = get_text(columns[0])
        columns = columns[1:]
        
    start = get_text(columns[0])
    end = get_text(columns[1])
    level = get_text(columns[2])
    
    data.append([country, place, start, end, level])
    
df = pd.DataFrame(data, columns=["Country", "Place", "Start date", "End date", "Level"])
df.to_csv("data/quarantine_dates.csv", index=False)
df

           Country      Place  Start date    End date     Level
0          Algeria    Algiers  2020-03-23  2020-04-14      City
1          Algeria      Blida  2020-03-23  2020-04-14      City
2        Argentina             2020-03-19  2020-04-12  National
3        Australia             2020-03-23  2020-04-24  National
4          Austria             2020-03-16  2020-04-13  National
..             ...        ...         ...         ...       ...
96   United States   New York  2020-03-20  2020-03-29     State
97   United States     Oregon  2020-03-24  2020-04-14     State
98   United States  Wisconsin  2020-03-24  2020-04-24     State
99       Venezuela             2020-03-17  2020-04-19  National
100       Zimbabwe             2020-03-30  2020-04-12  National

[101 rows x 5 columns]