In [1]:
import requests
import pandas as pd

URL = "https://yastat.net/s3/milab/2020/podomam/data/index_data.json"
data = requests.get(URL).json()

df = pd.DataFrame([[v['date'], city, v['value']] for city, values in data.items() for v in values])
df.columns = ['date', 'city', 'value']
df.to_csv('data/self_isolation_rus.csv', index=False)

df

           date             city  value
0    2020-03-02  Санкт-Петербург    0.7
1    2020-03-03  Санкт-Петербург    0.6
2    2020-03-04  Санкт-Петербург    0.6
3    2020-03-05  Санкт-Петербург    0.6
4    2020-03-06  Санкт-Петербург    0.6
..          ...              ...    ...
715  2020-04-02           Россия    3.6
716  2020-04-03           Россия    3.5
717  2020-04-04           Россия    3.9
718  2020-04-05           Россия    4.1
719  2020-04-06           Россия    3.2

[720 rows x 3 columns]